version: '3'
services:
  azuracast:
    image: azuracast/azuracast:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mySecureRootPassword
      - MYSQL_DATABASE=azuracast_db
      - MYSQL_USER=azuracast_user
      - MYSQL_PASSWORD=mySecurePassword
    ports:
      - "80:80"
      - "8000:8000"
    restart: always
    volumes:
      - azuracast_data:/var/azuracast
volumes:
  azuracast_data:
    external: true  # Railway automatically handles this
